version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hooks
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - hook
    depends_on:
      - db
      - kafka

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    working_dir: /app
    volumes:
      - ./frontend:/app
    networks:
      - hook

  webserver:
    image: nginx:latest
    ports:
      - "1002:80"
      - "10023:443"
    volumes:
      - ./backend:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - api
    networks:
      - hook

  db:
    image: mariadb:10.7.8
    ports:
      - "10026:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: webhooks
    networks:
      - hook

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '10021:2181'
    networks:
      - hook
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '10022:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - hook

networks:
  hook:
    driver: bridge